# 项目启动环境
application:
  host: 127.0.0.1  # 主机ip 或者域名，默认0.0.0.0
  port: 8000 # 服务端口
  cors-allow-origin: "*" # 允许的跨域请求
  env: dev # dev prod 分别代表开发环境和正式环境
log:
  dir: temp/logs # 日志文件存放路径
jwt:
  secret: rankland # JWT 加密字符串
  timeout: 5 # 过期时间单位：小时

# redis 配置
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  database: 0
  max-retry: 3 # 重试次数

# postgresql 数据库配置
postgresql:
  username: postgres
  password: mushanpsql
  host: 127.0.0.1
  port: 5432
  dbname: rankland
  time-zone: Asia/Shanghai